export const REQUEST_LOCATION = 'REQUEST_LOCATION';
export const LOCATION_SUCCESS = 'LOCATION_SUCCESS';
export const LOCATION_ERROR = 'LOCATION_ERROR';
export const TOGGLE_LAYER = 'TOGGLE_LAYER';
export const CENTER_MAP = 'CENTER_MAP';
export const MOVE_MAP = 'MOVE_MAP';
export const MOVE_MARKER = 'MOVE_MARKER';
