server:
    build: .
    dockerfile: "server.Dockerfile"
    environment:
        MONGO_CONN: 'mongodb://mongo:27017/aircheck'
    ports: 
        -   "1234:1234"
    links:
        -   "mongo"

    restart: on-failure

mongo:
    image: mongo:3.2
    volumes:
        - /data/db